version: "3.7"

services:
  react:
    image: node:12-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend_react:/app
    container_name: test_react
    networks:
      - frontend-network

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: back_spring
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./DB_Mysql/:/var/lib/mysql"
    ports:
      - "3306:3306"
    container_name: test_mysql
    networks:
      - backend-network

  spring-boot:
    build:
      context: ./Backend_Spring/docker_test
      dockerfile: Dockerfile
    image: plee_auth
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: plee_auth
    restart: always
    depends_on:
      - database # 데이터베이스와 connection 요구
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://test_mysql:3306/back_spring?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - backend-network
      - frontend-network

networks:
  backend-network:
  frontend-network:

# container_name 컨테이너에 올린 후 이름
# 